### ISSUE TITLE
Support Symbols as event names.

### ISSUE THREAD

**Issue by briandipalma** [jacomyal/emmett#22]
What it says in the description :)

**Comment by Yomguithereal** [comment]
Hello @briandipalma. Have you tried symbols yet with `emmett`? My intuition is that it should actually work excepted if we base some condition upon `typeof x === 'string'`. But let me check that.

**Comment by Yomguithereal** [comment]
Ok, I just tried it and there is indeed a condition preventing that. Let me check the question with @jacomyal.

**Comment by Yomguithereal** [comment]
I've created a [branch](https://github.com/jacomyal/emmett/tree/symbols-support) where symbols are supported, if you need it quickly.

**Comment by briandipalma** [comment]
No rush, I just wanted to raise the issue. Thanks for the quick turn around, very impressive!
